[package]
name = "kexa-storage"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
sled = "0.34"
borsh = { workspace = true }
kexa-proto = { path = "../kexa-proto" }
