[package]
name = "kexa-consensus"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
sha2 = { workspace = true }
kexa-proto = { path = "../kexa-proto" }

[dev-dependencies]
hex = { workspace = true }
