[package]
name = "kexa-p2p"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow = { workspace = true }
borsh = { workspace = true }
bytes = { workspace = true }
kexa-proto = { path = "../kexa-proto" }

[dev-dependencies]
rand = { workspace = true }
